### PR TITLE
df plugin - option to remove old ReportReserved config

### PR DESCRIPTION
**Pull request by cmclaughlin**
I expanded on PR #107 by @dosercz by adding the `disable_report_reserved` option. For existing users who are running old versions of collectd, they can upgrade to the latest version of this formula and won't have anything break.  But those of us with newer versions of collectd can set `disable_report_reserved` in Pillar.

### CODE REVIEW

**Comment by cmclaughlin** [comment]
@javierbertoli @fintanmm @babilen I noticed you merged some other PRs... please take a look here.

**Comment by fintanmm** [comment]
Hi @cmclaughlin,

So will I merge PR #107 then this? 

Thanks
Fintan

**Comment by cmclaughlin** [comment]
@fintanmm this PR has the commit from PR #107, so merging this and closing the other would be sufficient.  Thanks!

**Comment by fintanmm** [comment]
Ok @cmclaughlin, I'm going to close PR #107. I'll leave this open for a bit to see if anyone has an issue with it. If not, I'll merge it.

**Pull request merged**
