### PR TITLE
Greatly improve apache plugin support

### PR DESCRIPTION
**Pull request by genuss**
Hi! That's me again.
I mention apache module support is very basic, so I made a patch.
I made it so that it's default config is backwards-compatible with the current one.

### CODE REVIEW

**Comment by puneetk** [comment]
This is nice, can you update the documentation to reflect how this should be used. No need to close the pull, just push up another commit or rebase

**Comment by genuss** [comment]
Sure!
Do you mean include it in ``README.rst``?

**Comment by puneetk** [comment]
yes please

**Comment by iggy** [comment]
Thanks a ton

**Comment by genuss** [comment]
You're always welcome!

**Pull request merged**
