### PR TITLE
Added support for the memcached plugin

### PR DESCRIPTION
**Pull request by bogdanr**

### CODE REVIEW

**Comment by bogdanr** [comment]
Any chance to merge this?

**Comment by fintanmm** [comment]
Hi @bogdanr,

Can this be broken into two PR's? One for the bind plugin and the other for memcached. 

Thanks
Fintan

**Comment by bogdanr** [comment]
Hello,

GitHub puts all the commits from a repo in the same PR even if I click the create PR button after I make the other commit. As you can see, there are separate commits spaced very far apart so the history would be fine.

**Comment by fintanmm** [comment]
OK @bogdanr, can you resolve the conflict in map.jinja? Then I will merge the PR.

**Pull request merged**
